org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.disableJdkImageTransform=true
flutter.compileSdkVersion=35
flutter.minSdkVersion=21
flutter.targetSdkVersion=35
org.gradle.java.home=/home/marcelo/.sdkman/candidates/java/17.0.15-tem
